name: Build image on pushing changes to master branch

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: calculator-cicd
  IMAGE: calculator-multiplier

  JAVA_TARGET_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_TARGET_VERSION }}

      - name: Read gradle environment
        run: |
          PROJECT_VERSION=$(./gradlew -q project_version | tail -n 1)
          SNAPSHOT=$(./gradlew -q snapshot | tail -n 1)
          PROJECT_NAME=$(./gradlew -q project_name | tail -n 1)
          echo ::set-env name=PROJECT_VERSION::$PROJECT_VERSION-$SNAPSHOT
          echo ::set-env name=PROJECT_NAME::$PROJECT_NAME
          echo "env.PROJECT_VERSION: $PROJECT_VERSION"
          echo "env.PROJECT_NAME: $PROJECT_NAME"

      - name: Write app version to application config
        run: |
          echo -e "\napp.version=\"$PROJECT_VERSION\"\n" >> src/main/resources/application.conf
          cat src/main/resources/application.conf

      - name: Run a clean build with gradlew
        run: ./gradlew clean build

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '289.0.0'
          service_account_email: ${{ secrets.GOOGLE_SERVICEACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SERVICEACCOUNT_KEY }}

      - name: Configure docker to use Google Container Registry
        run: gcloud auth configure-docker

      - name: Build docker image
        run: |
          docker build \
            --tag "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            -f Dockerfile \
            .
      - name: Publish Snapshot
        run: |
          docker push eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA
          docker tag \
            "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA" \
            "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:${PROJECT_VERSION}"
          docker push "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:${PROJECT_VERSION}"